# Site settings
title: Ali Abdelkader
author:
  name: Ali Abdelkader
  email: aly.abdelkader@aucegypt.edu
description: "My personal Blog"

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
